# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 364)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.numberOfParkingLineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.numberOfParkingLineedit.setObjectName("numberOfParkingLineedit")
        self.horizontalLayout.addWidget(self.numberOfParkingLineedit)
        spacerItem = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RandomCalculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.RandomCalculateButton.setObjectName("RandomCalculateButton")
        self.horizontalLayout.addWidget(self.RandomCalculateButton)
        spacerItem1 = QtWidgets.QSpacerItem(16, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.addPButton = QtWidgets.QPushButton(self.centralwidget)
        self.addPButton.setObjectName("addPButton")
        self.horizontalLayout.addWidget(self.addPButton)
        spacerItem2 = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.addSButton = QtWidgets.QPushButton(self.centralwidget)
        self.addSButton.setObjectName("addSButton")
        self.horizontalLayout.addWidget(self.addSButton)
        spacerItem3 = QtWidgets.QSpacerItem(13, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.specificPScalulateButton = QtWidgets.QPushButton(self.centralwidget)
        self.specificPScalulateButton.setObjectName("specificPScalulateButton")
        self.horizontalLayout.addWidget(self.specificPScalulateButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 6)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 6)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(6, 6)
        self.horizontalLayout.setStretch(7, 1)
        self.horizontalLayout.setStretch(8, 6)
        self.horizontalLayout.setStretch(9, 1)
        self.horizontalLayout.setStretch(10, 6)
        self.horizontalLayout.setStretch(11, 10)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.dataTable = QtWidgets.QTableWidget(self.centralwidget)
        self.dataTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(0)
        self.dataTable.setRowCount(0)
        self.dataTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.dataTable)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 15)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RandomCalculateButton.setText(_translate("MainWindow", "Calculate"))
        self.addPButton.setText(_translate("MainWindow", "P"))
        self.addSButton.setText(_translate("MainWindow", "S"))
        self.specificPScalulateButton.setText(_translate("MainWindow", "Calculate"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
